Even more services because I need help (#25)
* service: whoogle

* service: tandoor

* feat: restore pihole to k3s

* feat: linkding

* feat: replace tandoor for kitchen owl

* chore: yamlfmt

* feat: excalidraw

* feat: cloudbeaver

diff --git a/cluster/vaultwarden/backup-cloud-cron.yml b/cluster/vaultwarden/backup-cloud-cron.yml
--- a/cluster/vaultwarden/backup-cloud-cron.yml
+++ b/cluster/vaultwarden/backup-cloud-cron.yml
@@ -4,91 +4,7 @@ metadata:
   name: backup-cloud
   namespace: vaultwarden
 data:
-  backup.sh: |
-    #!/bin/bash
-
-    # TODO: Fix repetition
-
-    # Install dependencies
-    apt update
-    apt install -y jq
-    npm install -g @bitwarden/cli
-
-    email=$EMAIL
-    password=$PASSWORD
-    backup_folder="/backup"
-
-    mkdir -p $backup_folder
-
-    bw config server http://vaultwarden.vaultwarden
-
-    echo "Performing login..."
-    bw login $email $password --method 0 --quiet
-
-    if [[ $(bw status | jq -r .status) == "unauthenticated" ]]
-    then 
-        echo "ERROR: Failed to authenticate on vaultwarden"
-        exit 1
-    fi
-
-    # unlock the vault
-    session_key=$(bw unlock $password --raw)
-
-    # verify that unlock succeeded
-    if [[ $session_key == "" ]]
-    then 
-        echo "ERROR: Failed to authenticate."
-        exit 1
-    else
-        echo "Login successful."
-    fi
-
-    #Export the session key as an env variable (needed by BW CLI)
-    export BW_SESSION="$session_key" 
-
-    echo "exporting vault"
-    bw export --format json --output $backup_folder/backup.json
-
-    echo
-    echo "cloud import complete."
-
-    bw logout
-
-    echo
-    echo "logging into bitwarden cloud"
-
-    bw config server https://bitwarden.com
-
-    bw login $email $password --method 0 --quiet
-
-    if [[ $(bw status | jq -r .status) == "unauthenticated" ]]
-    then 
-        echo "ERROR: Failed to authenticate on bitwarden"
-        exit 1
-    fi
-
-    session_key=$(bw unlock $password --raw)
-
-    # verify that unlock succeeded
-    if [[ $session_key == "" ]]
-    then 
-        echo "ERROR: Failed to authenticate."
-        exit 1
-    else
-        echo "Login successful."
-    fi
-
-    export BW_SESSION="$session_key" 
-
-    echo "importing backup to cloud"
-    bw import bitwardenjson $backup_folder/backup.json
-
-    echo "backup complete"
-
-    rm -rf $backup_folder
-
-    bw lock
-    echo
+  backup.sh: "#!/bin/bash\n\n# TODO: Fix repetition\n\n# Install dependencies\napt update\napt install -y jq\nnpm install -g @bitwarden/cli\n\nemail=$EMAIL\npassword=$PASSWORD\nbackup_folder=\"/backup\"\n\nmkdir -p $backup_folder\n\nbw config server http://vaultwarden.vaultwarden\n\necho \"Performing login...\"\nbw login $email $password --method 0 --quiet\n\nif [[ $(bw status | jq -r .status) == \"unauthenticated\" ]]\nthen \n    echo \"ERROR: Failed to authenticate on vaultwarden\"\n    exit 1\nfi\n\n# unlock the vault\nsession_key=$(bw unlock $password --raw)\n\n# verify that unlock succeeded\nif [[ $session_key == \"\" ]]\nthen \n    echo \"ERROR: Failed to authenticate.\"\n    exit 1\nelse\n    echo \"Login successful.\"\nfi\n\n#Export the session key as an env variable (needed by BW CLI)\nexport BW_SESSION=\"$session_key\" \n\necho \"exporting vault\"\nbw export --format json --output $backup_folder/backup.json\n\necho\necho \"cloud import complete.\"\n\nbw logout\n\necho\necho \"logging into bitwarden cloud\"\n\nbw config server https://bitwarden.com\n\nbw login $email $password --method 0 --quiet\n\nif [[ $(bw status | jq -r .status) == \"unauthenticated\" ]]\nthen \n    echo \"ERROR: Failed to authenticate on bitwarden\"\n    exit 1\nfi\n\nsession_key=$(bw unlock $password --raw)\n\n# verify that unlock succeeded\nif [[ $session_key == \"\" ]]\nthen \n    echo \"ERROR: Failed to authenticate.\"\n    exit 1\nelse\n    echo \"Login successful.\"\nfi\n\nexport BW_SESSION=\"$session_key\" \n\necho \"importing backup to cloud\"\nbw import bitwardenjson $backup_folder/backup.json\n\necho \"backup complete\"\n\nrm -rf $backup_folder\n\nbw lock\necho\n"
 ---
 apiVersion: batch/v1
 kind: CronJob
diff --git a/cluster/vaultwarden/backup-local-cron.yml b/cluster/vaultwarden/backup-local-cron.yml
--- a/cluster/vaultwarden/backup-local-cron.yml
+++ b/cluster/vaultwarden/backup-local-cron.yml
@@ -4,82 +4,7 @@ metadata:
   name: backup-local
   namespace: vaultwarden
 data:
-  backup.sh: |
-    #!/bin/bash
-
-    # Install dependencies
-    apt update
-    apt install -y jq
-    npm install -g @bitwarden/cli
-
-    email=$EMAIL
-    password=$PASSWORD
-    encryption_password=$ENCRYPTION_PASSWORD
-    backup_folder=$BACKUP_FOLDER
-    attachments_folder=$ATTACHMENTS_FOLDER
-
-    if [ -z "$ENCRYPTION_PASSWORD" ] || [ -z "$BACKUP_FOLDER" ] || [ -z "$ATTACHMENTS_FOLDER" ]; then
-      echo "Error: One or more of the required environment variables" \ 
-          "(ENCRYPTION_PASSWORD, SAVE_FOLDER, ATTACHMENTS_FOLDER) are not set."
-      exit 1
-    fi
-
-    bw config server http://vaultwarden.vaultwarden
-
-    echo "Starting export script..."
-
-    if [[ $(bw status | jq -r .status) == "unauthenticated" ]]
-    then 
-        echo "ERROR: Failed to authenticate."
-        echo
-        exit 1
-    fi
-
-    #Unlock the vault
-    session_key=$(bw unlock $password --raw)
-
-    #Verify that unlock succeeded
-    if [[ $session_key == "" ]]
-    then 
-        echo "ERROR: Failed to authenticate."
-        echo
-        exit 1
-    else
-        echo "Login successful."
-        echo
-    fi
-
-    #Export the session key as an env variable (needed by BW CLI)
-    export BW_SESSION="$session_key" 
-
-    echo "Performing vault exports..."
-
-    # 1. Export the personal vault 
-    if [[ ! -d "$backup_folder" ]]
-    then
-        echo "ERROR: Could not find the folder in which to save the files."
-        echo
-        exit 1
-    fi
-
-    echo 
-    echo "Exporting personal vault to a password-encrypted file..."
-    bw export --format encrypted_json --password $encryption_password --output $backup_folder/backup.json
-
-    # Perform attachments backup
-    if [[ $(bw list items | jq -r '.[] | select(.attachments != null)') != "" ]]
-    then
-        echo
-        echo "Saving attachments..."
-        bash <(bw list items | jq -r '.[] 
-        | select(.attachments != null) 
-        | "bw get attachment \"\(.attachments[].fileName)\" --itemid \(.id) --output \"'$attachments_folder'\(.name)/\""' )
-
-    echo
-    echo "vault export complete."
-
-    bw lock 
-    echo
+  backup.sh: "#!/bin/bash\n\n# Install dependencies\napt update\napt install -y jq\nnpm install -g @bitwarden/cli\n\nemail=$EMAIL\npassword=$PASSWORD\nencryption_password=$ENCRYPTION_PASSWORD\nbackup_folder=$BACKUP_FOLDER\nattachments_folder=$ATTACHMENTS_FOLDER\n\nif [ -z \"$ENCRYPTION_PASSWORD\" ] || [ -z \"$BACKUP_FOLDER\" ] || [ -z \"$ATTACHMENTS_FOLDER\" ]; then\n  echo \"Error: One or more of the required environment variables\" \\ \n      \"(ENCRYPTION_PASSWORD, SAVE_FOLDER, ATTACHMENTS_FOLDER) are not set.\"\n  exit 1\nfi\n\nbw config server http://vaultwarden.vaultwarden\n\necho \"Starting export script...\"\n\nif [[ $(bw status | jq -r .status) == \"unauthenticated\" ]]\nthen \n    echo \"ERROR: Failed to authenticate.\"\n    echo\n    exit 1\nfi\n\n#Unlock the vault\nsession_key=$(bw unlock $password --raw)\n\n#Verify that unlock succeeded\nif [[ $session_key == \"\" ]]\nthen \n    echo \"ERROR: Failed to authenticate.\"\n    echo\n    exit 1\nelse\n    echo \"Login successful.\"\n    echo\nfi\n\n#Export the session key as an env variable (needed by BW CLI)\nexport BW_SESSION=\"$session_key\" \n\necho \"Performing vault exports...\"\n\n# 1. Export the personal vault \nif [[ ! -d \"$backup_folder\" ]]\nthen\n    echo \"ERROR: Could not find the folder in which to save the files.\"\n    echo\n    exit 1\nfi\n\necho \necho \"Exporting personal vault to a password-encrypted file...\"\nbw export --format encrypted_json --password $encryption_password --output $backup_folder/backup.json\n\n# Perform attachments backup\nif [[ $(bw list items | jq -r '.[] | select(.attachments != null)') != \"\" ]]\nthen\n    echo\n    echo \"Saving attachments...\"\n    bash <(bw list items | jq -r '.[] \n    | select(.attachments != null) \n    | \"bw get attachment \\\"\\(.attachments[].fileName)\\\" --itemid \\(.id) --output \\\"'$attachments_folder'\\(.name)/\\\"\"' )\n\necho\necho \"vault export complete.\"\n\nbw lock \necho\n"
 ---
 apiVersion: batch/v1
 kind: CronJob
